### ISSUE TITLE
Support for CI enviroments

### ISSUE THREAD

**Issue by marcorivm** [quasarframework/app-extension-dotenv#11]
Hi guys, great work with the extension I have been using it for a project recently and works great, there is one thing I'm not getting, and it's CI and CD support. On environments like netlify you don't have a .env file but are able to set environment variables to be used on the build process.

When building on a CI environment since there is no .env file and it's not practical (or secure) to pick all process.env variables available the env variables set using Netlify console (or other providers) are lost and not available after build.

I had built an extension for quasar pre v1.0 which addressed this issue using a .env.example file as a key dictionary to look for system env values at build time and include them on the process. https://github.com/CarbonoDev/quasar-dotenv

Could we do something similar here? Or is there a way to support this that I'm missing?

**Comment by hawkeye64** [comment]
I am wondering if you have looked at the QEnv app extension (I also wrote and maintain): https://github.com/quasarframework/app-extension-qenv. It's better at variables with different environments (and only one file to maintain). It doesn't do environment variables, which is an interesting concept. I'd like to hear more about it, but think this is more appropriate for QEnv to handle.

**Comment by marcorivm** [comment]
Yep I looked a it, but I don't think it fits the problem I'm talking about,
because although in some CI environments it's possible to write files with
env variables it's not the case on all, and those env files shouldn't be
committed because they will have API Keys and probably other secret values
(which given the front-end nature will end up on the final build but at
least not in the repo). What do you think of my implementation on the pre
v1 plug-in using env.example as a dictionary for taking variables directly
from system env variables. If you like it/agree I can write a PR to
implement it, I will update my own plug-in to do it otherwise but I don't
see much value in having both doing almost the same thing.

**Comment by marcorivm** [comment]
I think this could also be a totally different extension that just loads variables into process.env from the system environment variables using somekind of configuration dictionary to know which ones to load. wdyt?

**Comment by hawkeye64** [comment]
I think a separate app-ext would be best. Not to redefine the behavior of dotenv (app-ext as a wrapper).

**Comment by marcorivm** [comment]
I have created a new extension for this issue, I'm working on the docs, but it basically uses .env.example as a key dictionary to load variables from the system environment 

https://github.com/marcorivm/quasar-app-extension-system-environment-variables
