### ISSUE TITLE
Variables from .env file are not available in quasar.conf.js

### ISSUE THREAD

**Issue by MurzNN** [quasarframework/app-extension-dotenv#13]
I have successfully installed `@quasar/dotenv` app Extension to my Quasar, create `.env` file with simple string:
```
APP_PORT=12345
```
And type in my `quasar.conf.js`: 
```
    devServer: {
      port: process.env.APP_PORT,
    },
```
But it stay empty. My `quasar.extensions.json` is:
```
{
  "@quasar/dotenv": {
    "env_development": ".env",
    "env_production": ".env",
    "common_root_object": "none",
    "create_env_files": true,
    "add_env_to_gitignore": true
  }
}
```
and when starting Quasar I see 
```
 app:extension Running "@quasar/dotenv" Quasar App Extension... +0ms
 app:quasar-conf Reading quasar.conf.js +11ms
```
Please descripbe where can be the problem and why the `APP_PORT` env variable is not filled?

**Comment by smolinari** [comment]
Did you possibly miss this part of the instructions? 😀 

> Be aware, if you have something like this in your .env:
>
> APP_PORT=4000
>
> Then you will need to use the parseInt() function as it will be propogated to the browser code as a string.

Scott

**Comment by MurzNN** [comment]
`parseInt()` isn't help, because `process.env.APP_PORT` is `undefined`, regarding to `console.log(process.env.APP_PORT)` output.

**Comment by smolinari** [comment]
Hmm. ok. I forgot this app extension is only for passing environment variables to the browser. `quasar.conf.js` is processed on the server, so you won't see the data on `process.env` at that point when the file is processed.

You can do this and get the same result. 

```javascript
    devServer: {
      // https: true,
      port: process.env.NODE_ENV === 'development' ? 9090 : 8080,
      open: true // opens browser window automatically
    },
```

where `9090` would be the port you want to have.

Scott

**Comment by MurzNN** [comment]
I need to have custom port, fillable from `.env` file, not static hardcoded values. So, for use env values in `quasar.conf.js` will be better to use separate node.js `dotenv` module?

Please describe in readme, that this extension not work in backend (especially in `quasar.conf.js`), because this file is first place, where most of users will try it :)

**Comment by smolinari** [comment]
I may also be missing something too, as I was also thinking .env key values would be available on the node side too. Maybe @hawkeye64 can clarify better. 

Scott

**Comment by hawkeye64** [comment]
This puts variables, at **build time** into something like `build -> env` - like I said, at build time. So, they are always static, but available to browser via webpack.

**Comment by MurzNN** [comment]
Solution for this issue is adding to top of `quasar.conf.js` file (before `module.exports`) code, that parse `.env` file in server side, and add variables to `process.env`:
```
const DotEnv = require('dotenv')

if(parsedEnv = DotEnv.config().parsed) {
  for (let key in parsedEnv) {
    process.env[key] = parsedEnv[key]
  }
}
```
After this you can use `.env` values in other places, for example assign Quasar dev port number from variable `APP_PORT`:
```
    devServer: {
      https: false,
      port: process.env.APP_PORT ? parseInt(process.env.APP_PORT) : 8080,
      open: true // opens browser window automatically
    },
```

**Comment by hawkeye64** [comment]
This app extension is for the browser, not build time. You will have to come up with your own implementation for that. By the time this app extension is called by Quasar, it would be too late to make changes to the config.
That being said, you can add code to `quasar.conf.js` to do this.
In the docs, look for the `beforeDev` and `beforeBuild` hooks.

**Comment by DarkLite1** [comment]
I was also under the impression that it would be possible to use a `.env` file generated by the official Quasar app extension `( @quasar/quasar-app-extension-doten`)  to set a port in the `quasar.conf.js` file and other places. It should be more clear from the docs that this is not possible.

The workaround, mentioned by @MurzNN , is to install the default `dotenv` package from npm and then add them in the `quasar.conf.js` file.

However there appears to be another official extension called [app-extension-qenv](https://github.com/quasarframework/app-extension-qenv) that offers this. If you look at the answer [here](https://github.com/quasarframework/app-extension-qenv/issues/8) you can access the variables within the `quasar.conf.js` file like this:

> So, no. You cannot access `process.env` from within `quasar.conf.js`. However, you can access everything that will be going into `process.env` -- use `build.env` from within `quasar.conf.js`. Everything in `build.env` will be converted to `process.env` (build-time, vs run-time).

**Comment by aretw0** [comment]
**On 'quasar dev' I need to trigger the hot-reload by saving `quasar.conf.js` for my env variables come into existence.**

So far I don't know the behavior of this in the build.

**Comment by BenceSzalai** [comment]
[DarkLite1 commented on May 5](https://github.com/quasarframework/app-extension-dotenv/issues/13#issuecomment-623998041):
> However there appears to be another official extension called [app-extension-qenv](https://github.com/quasarframework/app-extension-qenv) that offers this. If you look at the answer [here](https://github.com/quasarframework/app-extension-qenv/issues/8) you can access the variables within the `quasar.conf.js` file like this:
> 
> > So, no. You cannot access `process.env` from within `quasar.conf.js`. However, you can access everything that will be going into `process.env` -- use `build.env` from within `quasar.conf.js`. Everything in `build.env` will be converted to `process.env` (build-time, vs run-time).

I see no difference between the behaviour of `@quasar/quasar-app-extension-dotenv` and `@quasar/quasar-app-extension-qenv`. They both do the same when it comes to `build.env`. Compare qenv's [index.js#L57](https://github.com/quasarframework/app-extension-qenv/blob/dev/app-extension/src/index.js#L57) & [index.js#L70](https://github.com/quasarframework/app-extension-qenv/blob/dev/app-extension/src/index.js#L70) to dotenv's [index.js#L66](https://github.com/quasarframework/app-extension-dotenv/blob/dev/app-extension/src/index.js#L66) & [index.js#L79](https://github.com/quasarframework/app-extension-qenv/blob/dev/app-extension/src/index.js#L79). They do the same.

But this still doesn't make the variables defined in `.env` usable inside `quasar.conf.js`. This cannot even possibly happen, as `quasar.conf.js` is processed **before** the app extension's code is loaded. Trying to access the `build` object in `quasar.conf.js` causes:
```
 App · Reading quasar.conf.js
[  ReferenceError: build is not defined
...
]
 App · ⚠️  [FAIL] quasar.conf.js has JS errors
```

I quess what the referenced comment meant is about the other way around: you can define `build.env` properties in `quasar.conf.js`, and they will be available during runtime inside `process.env`. So add this to `quasar.conf.js`:
```
...
build: { ...
      env: {
        additional_env_item: 'value'
      }
... }
...
```
and use it during runtime as : `process.env.additional_env_item`

The workaround seems to be this: [MurzNN commented on Apr 16](https://github.com/quasarframework/app-extension-dotenv/issues/13#issuecomment-614644327).

**Comment by hawkeye64** [comment]
@BenceSzalai The above is exactly what quasar-app-extension-dotenv and quasar-app-extension-qenv do -- adds to `build -> env`. As I mentioned above, this is a timing issue. You can't access the variables until they are there and this is based on @quasar/app run-time hooks . Look for the `beforeDev` and `beforeBuild` hooks in the Quasar docs. You can add these to your quasar.conf.js and at that point access the data.

**Comment by BenceSzalai** [comment]
Yep, all is clear. Just looked like there was a lot of confusion, and once I've figured it out I wanted to help the next one in my shoes. :)
