### ISSUE TITLE
Does not install

### ISSUE THREAD

**Issue by damko** [quasarframework/app-extension-dotenv#17]
I'm very new to Quasar so it is possible I'm missing something.

**Describe the bug**
I've followed the [instructions](https://quasar.dev/app-extensions/introduction) but the installation breaks

**To Reproduce**
1. From terminal, run
`quasar ext add dotenv`
2. I get:
```
app:spawn [sync] Running "npm install --save-dev quasar-app-extension-dotenv" +0ms
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/quasar-app-extension-dotenv - Not found
```
In fact https://registry.npmjs.org/quasar-app-extension-dotenv returns 404

**Desktop:**
 - OS: Debian buster
- Quasar info output:
```
Operating System - Linux(4.19.15-1) - linux/x64
NodeJs - 12.14.0

Global packages
  NPM - 6.13.4
  yarn - 1.21.1
  @quasar/cli - 1.0.3
  cordova - Not installed

Important local packages
  quasar - 1.5.9 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app - 1.4.3 -- Quasar Framework local CLI
  @quasar/extras - 1.3.3 -- Quasar Framework fonts, icons and animations
  vue - 2.6.11 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.1.3 -- Official router for Vue.js 2
  vuex - 3.1.2 -- state management for Vue.js
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed
  @babel/core - 7.7.7 -- Babel compiler core.
  webpack - 4.41.3 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.9.0 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 4.3.1 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.6.2 -- Script for registering service worker, with hooks

Quasar App Extensions
  *None installed*

Networking
<cut>
```

**Work around**
I managed to install the extension in this way:
```
npm i --save-dev @quasar/quasar-app-extension-dotenv
quasar ext invoke @quasar/dotenv
```
I see the ext listed as installed:
```
> quasar ext
 app:extension-manager Listing installed App Extensions +0ms

Extension name: @quasar/dotenv
Extension prompts: {
  "env_development": ".env.development",
  "env_production": ".env",
  "common_root_object": "TEST",
  "create_env_files": true,
  "add_env_to_gitignore": true
}
```
and `process.env.TEST` does contain the variables present in `.env` as expected. 
__However I can not uninstall it__:
```
> quasar ext remove dotenv
 app:extension Uninstalling "dotenv" Quasar App Extension +0ms

 app:extension ⚠️  Quasar App Extension "quasar-app-extension-dotenv" is not installed... +1ms
```

**Comment by smolinari** [comment]
Try `quasar ext add @quasar/dotenv`.

Also try to ask the question in the forum or on Discord first and we'll see if it is your setup or usage or a bug. Once we nail it down and it is a bug, we'll ask you to make an issue. Thanks! :smiley:

https://chat.quasar.dev
https://forum.quasar.dev

Scott

**Comment by damko** [comment]
thanks for your fast reply.

Yes `quasar ext add @quasar/dotenv` works and then even uninstalling works.

About this ticket, I believe that all is due to the 404

**Comment by smolinari** [comment]
The issue is, there is no package under `dotenv`. It's an official App Extension, so falls under `@quasar/dotenv`. Note the `@quasar`.....

Scott

**Comment by hawkeye64** [comment]
@damko For future reference: https://github.com/quasarframework/app-extension-dotenv/tree/dev/app-extension

**Comment by StefanNeuser** [comment]
Hi, i started a PR https://github.com/quasarframework/app-extension-dotenv/pull/23 but other question. I want to use my forked version as a extension. The installation via yarn worked with these line in package.json:

"@quasar/quasar-app-extension-dotenv": "https://github.com/StefanNeuser/app-extension-dotenv",

The changes are loaded and are located in the same folder under node_modules/@quasar/....

<img width="394" alt="Screenshot 2020-07-01 at 12 04 12" src="https://user-images.githubusercontent.com/2176503/86231598-19766e80-bb93-11ea-8140-007154943151.png">

But what i dont understand why it's not working?

<img width="608" alt="Screenshot 2020-07-01 at 12 04 28" src="https://user-images.githubusercontent.com/2176503/86231634-22ffd680-bb93-11ea-8f8b-56f5cc17a7fe.png">

I really appreciate any infos why forks of the extensions is not working or a review of my PR @hawkeye64

**Comment by smolinari** [comment]
Jeff is currently on vacation. He'll be back next week.

Scott

**Comment by hawkeye64** [comment]
@StefanNeuser This is a forked version? You will have to use a different name for your version. You won't be able to publish to the `@quasar` namespace because we own it on NPM. If you haven't published to NPM and are still in testing phase, you can use something like `yarn link` to do something like an install, then you can run `quasar ext invoke <name>`, which does everything except for the actual install (ie: it only does the quasar portion of the install). Also, the beginning parts of the name **MUST** begin with `quasar-app-extension` unless it's an official app ext, then if will also be prefixed by `@quasar/`
