### ISSUE TITLE
Trying to override DEV=true results in string instead of boolean

### ISSUE THREAD

**Issue by FrittenKeeZ** [quasarframework/app-extension-dotenv#18]
**Describe the bug**
Boolean variables from `.env` are parsed to strings.

**To Reproduce**
1. Install extension
2. Create an `.env` file with sole content `DEV=true`
3. Log content of `process.env` anywhere
4. See that `DEV` is a string instead of a boolean.

**Expected behavior**
Booleans should be parsed correctly.

**Screenshots**
![quasar-env-dev](https://user-images.githubusercontent.com/1186125/77651738-857e8080-6f6d-11ea-8f0b-4d0840df3257.png)

**Comment by hawkeye64** [comment]
@FrittenKeeZ Please refer to the docs, which says:
```
Be aware, if you have something like this in your .env:

APP_PORT=4000

Then you will need to use the parseInt() function as it will be propagated to the browser code as a string.
```
This is an issue with webpack, not the dotenv app extension.
