### ISSUE TITLE
Can I use this for src-cordova/build.json?

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/app-extension-dotenv#2]
Hi, I don't have much experience with `.env` files outside of my Laravel time 3 years ago (so it's all kinda fuzzy)

## My setup

With Cordova to publish Android apps, they need to be signed with a private key from a local keystore.
In the Quasar documentation, [the method explained here](https://v1.quasar-framework.org/quasar-cli/developing-mobile-apps/publishing-to-store#Android-Publishing) is kind of elaborate and can be solved waaaay easier by just adding your local keystore information inside a `src-cordova/build.json` file.

This is also explained in the [Cordova documentation](https://cordova.apache.org/docs/en/latest/guide/platforms/android/index.html#signing-an-app) and a build file would look like this:
```json
{
    "android": {
        "debug": {
            "keystore": "../android.keystore",
            "storePassword": "android",
            "alias": "mykey1",
            "password" : "password",
            "keystoreType": ""
        },
        "release": {
            "keystore": "../android.keystore",
            "storePassword": "",
            "alias": "mykey2",
            "password" : "password",
            "keystoreType": ""
        }
    }
}
```

I've been successfully signing all my Quasar cordova android apps with such a build.json file and just the regular Quasar CLI build command for cordova.

However, I've had to `.gitignore` this build.json file because it has a password.

## My question

Is there any way to extract just the password of this `build.json` file into an environment file with this app extension?

**Comment by hawkeye64** [comment]
No, you would need to create a different app extension that could do this.
