### ISSUE TITLE
Wrong installation instruction

### ISSUE THREAD

**Issue by caowenwei** [quasarframework/app-extension-dotenv#20]
For a legitimate bug, in order to process faster, please go here https://codesandbox.io/s/qcalendar-bx1y7, fork the codesandbox, add code to reproduce the bug and submit link here:

**Describe the bug**
On the npm page it says:
Install
quasar ext add dotenv
But if you run this, npm won't find this package:
error An unexpected error occurred: "https://registry.npmjs.org/quasar-app-extension-dotenv: Not found".

After reading quasar app extension introduction https://quasar.dev/app-extensions/introduction, I realized it has to be:
quasar ext add @quasar/dotenv

You may want to change this confusing instruction on the npm page, or fix quasar cli so npm can recognize the correct name of this extension.

**Comment by hawkeye64** [comment]
That was fixed some time ago. Maybe your page is cached?

![image](https://user-images.githubusercontent.com/10262924/79266703-3ed9c300-7e55-11ea-8d0a-70a2e462f649.png)

![image](https://user-images.githubusercontent.com/10262924/79266735-4b5e1b80-7e55-11ea-9eb4-c4ab06dedda9.png)

Or, is there another location that I missed?

oh, wait, you said the NPM page, which means it needs to be published to get it. Ok. :(

**Comment by hawkeye64** [comment]
Fixed with v1.0.1 release

**Comment by caowenwei** [comment]
> Fixed with v1.0.1 release
yes. got it now. thanks.
