### ISSUE TITLE
Not able to build copy with .env.staging

### ISSUE THREAD

**Issue by cristal2431** [quasarframework/app-extension-dotenv#21]
How do i build a copy with .env.staging

**Comment by hawkeye64** [comment]
This app-extension can only handle 2 environments. If you need more environments, use the qenv app-extension.
https://github.com/quasarframework/app-extension-qenv

**Comment by Moongazer** [comment]
Seriously?!? This information should definitively become part of the documentation! Lost much time trying to figure out how to pass the `env_*` keys to quasar on the command line... :-(
```
{
  "@quasar/dotenv": {
    "env_beta": "config.beta.env",
    "env_development": "config.development.env",
    "env_production": "config.production.env",
    "env_staging": "config.staging.env",
  }
}
```

**Comment by hawkeye64** [comment]
@Moongazer The upcoming v2 of @quasar/app will make these app-extensions redundant. They will convert to the new way to stay compatible, but you will be able to modify quasar.conf.js for your own needs as per .env files and settings with as many different ways and permutations you can think of.

**Comment by Moongazer** [comment]
Oh ok, that's good to hear. Thank you very much for the feedback! (And apologize for the a-bit-too-frustrated post earlier)

**Comment by hawkeye64** [comment]
@Moongazer No problem. Been in that situation many times.
I will try to find time to improve the docs.

**Comment by dalezak** [comment]
@hawkeye64 what was the solution for supporting `env_staging`? Running into the same problem myself.

**Comment by dalezak** [comment]
Would this PR https://github.com/quasarframework/app-extension-dotenv/pull/26 allow `.en.staging` to work for `Staging` environment?
