### ISSUE TITLE
[Question] Reload app when .env file are modified ?

### ISSUE THREAD

**Issue by J3m5** [quasarframework/app-extension-dotenv#24]
Hi, is there a way to make the app reload when one of the .env file has been modified ?

**Comment by hawkeye64** [comment]
@J3m5 Sorry, but no. The app-ext is run via the q/app and only gets run once during either `quasar dev` or `quasar build`. However, I can discuss with Razvan when he gets well and is back just in case there is some way of keeping something alive and having quasar regenerate the build.

**Comment by J3m5** [comment]
Ok, thanks.
I'm wondering if it could be done with an option in the quasar.config file.
We could just add a list of files that would be watched and would trigger the build, like it's done for the quasar.conf file.
Then the extension could automatically modify the config and add the files if there are not defined there.
What do you think ?

**Comment by hawkeye64** [comment]
@J3m5 I definitely think there is a possibility there. Will have to play around with it a bit.

**Comment by hawkeye64** [comment]
If you find a webpack plugin, let me know so I can document it. Otherwise, I think webpack ignores dotfiles by default.
