### ISSUE TITLE
QENV bug or missunderstood

### ISSUE THREAD

**Issue by StefanNeuser** [quasarframework/app-extension-dotenv#25]
Hi @hawkeye64 , thank you for merging my last PR. I have a question and maybe it's a bug. I have the following npm scripts:

```
    "dev": "QENV=development quasar dev",
    "dev-build": "QENV=development quasar build",
    "prod": "QENV=production quasar build",
```

when i run `yarn dev-build` i want to build the app in `dist/spa` with the .env.dev settings but it just load the .env. The QENV is not present. I also can't find some QENV usages in the source-code.

Here are my extension settings:

```
  "@quasar/dotenv": {
    "env_development": ".env.dev",
    "env_production": ".env"
  }
```

Maybe you can give you hint :-)

Best regards from Germany,

Stefan

**Comment by hawkeye64** [comment]
@StefanNeuser `quasar/qenv` and `@quasar/dotenv` are two different app extensions. The first part of your text above is what you'd do for qenv.
```
    "dev": "QENV=development quasar dev",
    "dev-build": "QENV=development quasar build",
    "prod": "QENV=production quasar build",
```
Do you mean to install qenv and not dotenv extsion?
Docs are here: https://github.com/quasarframework/app-extension-qenv/tree/dev/app-extension

**Comment by hawkeye64** [comment]
Btw, the dotenv app extension is just a wrapper around the popular dotenv npm package.
The qenv app extension is written from scratch, and imo, is less optionated and uses a single file for all settings.

**Comment by StefanNeuser** [comment]
That's it, i mixed it up! Thanks. Now i'm using the QENV package which is much better for my use-case
