### ISSUE TITLE
Add support for variable replacement ${FOO_BAR}

### ISSUE THREAD

**Issue by FrittenKeeZ** [quasarframework/app-extension-dotenv#29]
**Is your feature request related to a problem? Please describe.**
I'm combining Laravel and Quasar in the same project, and since `APP_URL` already exists in `process.env.APP_URL`, it would be nice to be able to do `API_URL="${APP_URL}"` when including Laravel's env file, to reuse the same variable.

**Describe the solution you'd like**
When looping through the parsed variables, check and replace pattern in the values.

**Describe alternatives you've considered**
Duplicating the value.

**Additional context**
Regex to match the variable pattern: `\${[A-Z]+(_?[A-Z]+)*}`

**Comment by hawkeye64** [comment]
@FrittenKeeZ You may be interested in this app extension: https://www.npmjs.com/package/quasar-app-extension-dotenv-plus

**Comment by FrittenKeeZ** [comment]
@hawkeye64 looking through the source for that package, it doesn't support the feature I describe, only the ability to have multiple `.env` files loaded in priority.

**Comment by hawkeye64** [comment]
@FrittenKeeZ k, I thought that's what that one did. I think this could be a great idea (for quasar-app-extension-qenv as well). We just need to find a way of doing it such that is compatible across all platforms.

**Comment by hawkeye64** [comment]
@FrittenKeeZ Done in release v1.1.0
