### ISSUE TITLE
The env vars are not available in quasar.conf.js

### ISSUE THREAD

**Issue by kwarnkham** [quasarframework/app-extension-dotenv#34]
I have common_root_object set.
But that object is not available in quasar.conf.js

**Comment by hawkeye64** [comment]
@kwarnkham It doesn't write to quasar.conf.js, it's "baked" into your app at build-time
You can do the same thing inside quasar.con.js -> build -> env
The app extension just makes it more convenient.
In the browser, you should be able to `console.log(process.env.MyRootObject)` and see results (change MyRootObject to name of your root object)
