### ISSUE TITLE
Rebuild Quasar when .env changes

### ISSUE THREAD

**Issue by FrittenKeeZ** [quasarframework/app-extension-dotenv#38]
**Is your feature request related to a problem? Please describe.**
Whenever you change the `.env` file, you have to restart `quasar dev` before the changes take effect.

**Describe the solution you'd like**
Is it possible to have this package instruct Quasar to reload the `.env` file and rebuild if it changes?

**Describe alternatives you've considered**
I honestly don't know if there're any other approaches, but I do know that Nuxt is able to detect changes to `.env` and force rebuild.

**Comment by hawkeye64** [comment]
@FrittenKeeZ You can find out why here: https://stackoverflow.com/a/60974708/5359558
