### ISSUE TITLE
Existing environment variables are not taken into account

### ISSUE THREAD

**Issue by ntraut** [quasarframework/app-extension-dotenv#39]
For a legitimate bug, in order to process faster, please go here https://codesandbox.io/s/qcalendar-bx1y7, fork the codesandbox, add code to reproduce the bug and submit link here:

**Describe the bug**
If one set an environment variable instead of putting it in the .env file, the extension doesn't read it unlike the original dotenv package.

**To Reproduce**
Create a quasar app with `console.log(process.env.MyData)` somewhere in the code.
In bash do:
```
export MyData="something"
quasar dev
```
In the navigator console nothing is output or the value defined in .env file. 

**Expected behavior**
The environment variable should have the priority so we should have "something" in the console.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Version any

**Comment by aasiph** [comment]
You need to go through this screencast [https://quasarcast.com/quasar-extensions/quasar-extensions-dotenv-environment-variables](url)

**Comment by ntraut** [comment]
Hello, the link is not working but I found the video at https://www.youtube.com/watch?v=SR_2vbTlF78.
The video explains how to deal with a .env file but not how the extension deals with environment variables. Since this extension is claiming to be an extension of the popular dotenv package I am expecting it to have the same behaviour, but maybe there is something that I misinterpreted?

**Comment by hawkeye64** [comment]
@ntraut https://github.com/quasarframework/app-extension-dotenv/blob/dev/app-extension/src/index.js#L14
