### ISSUE TITLE
Create "basic" dotenv files.

### ISSUE THREAD

**Issue by nothingismagick** [quasarframework/app-extension-dotenv#4]
I think it would be helpful to create base files for the user. Since quasar is smart enough not to overwrite files that exist (and prompts the user) creating these files would make the extension "better" and offer a template for those who are new to dotenv

https://forum.quasar-framework.org/topic/3309/v1-a-guide-for-quasar-dotenv

**Comment by hawkeye64** [comment]
fixed in 1.0.0-beta.5
