### ISSUE TITLE
.git directory in node_modules

### ISSUE THREAD

**Issue by steveclarke** [quasarframework/app-extension-dotenv#5]
After installing the extension, if I do a later `npm install` I get the following error:

![2019-03-25 at 3 41 PM](https://user-images.githubusercontent.com/1305/54943618-a05e8500-4f14-11e9-83a1-20262bcc7c8d.png)

When I navigate to `node_modules/@quasar/quasar-app-extension-dotenv/` and do a `ls -a` I see that there's a `.git` directory there.

When I delete this `.git` directory, I can now do `npm install`. 

Wondering if the `.git` directory should be added to the `.npmignore` file?

**Comment by hawkeye64** [comment]
Fixed in v1.0.0-beta.8
Thanks for finding this issue.

**Comment by hailwood** [comment]
@hawkeye64 looks like this issue is back in v1.0.0-beta.9?

**Comment by hawkeye64** [comment]
@hailwood Verified it is not there. Because it's a dot-file, maybe it doesn't get removed properly on update? Would you mind removing your node_modules, `yarn install` or `npm install` and report back to me if the issue remain? Many thanks.

**Comment by hailwood** [comment]
Hi @hawkeye64 

It's definitely being pulled it via the npm install, see below.

![image](https://user-images.githubusercontent.com/709773/57116875-0a880680-6dac-11e9-9e97-8802f13870c9.png)

My package.json contains `"@quasar/quasar-app-extension-dotenv": "^1.0.0-beta.9"`

I believe it's something to do with hooks?
https://unpkg.com/@quasar/quasar-app-extension-dotenv@1.0.0-beta.9/.git/hooks/README.sample
That's the only directory/file in the `.git` directory.

**Comment by hawkeye64** [comment]
Interesting. I'll have to investigate this some more.

**Comment by hawkeye64** [comment]
yep, got another fix. Coming sometime today.

**Comment by hawkeye64** [comment]
Fixed in beta.10 - let me know if it's working out for you.

**Comment by hailwood** [comment]
Perfect thanks @hawkeye64,

Issue can now be closed.

**Comment by hawkeye64** [comment]
Perfect. Thanks!
