### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by mitjarobic** [quasarframework/app-extension-dotenv#6]
Hi,

I do not see the variables in process.env.

Also, I opened the demo and there is no TEST property in the object.

![Screenshot from 2019-05-08 00-02-30](https://user-images.githubusercontent.com/1556158/57356354-1580c500-7125-11e9-96b5-00960221d208.png)

**Comment by hawkeye64** [comment]
You're right. I get the same results. I'll look into it. Thanks for reporting.

**Comment by irfandyj** [comment]
Hello, is this still a trouble? I tried using this extension, however it seems that my `.env` variables doesn't exist in `process.env` variable.

**Comment by feigner** [comment]
@jippy89, I thought I ran into this issue awhile back, but turned out that the contents of my `.env` file wasn't formatted correctly. After fixing my file, this extension is working as expected.

**Comment by irfandyj** [comment]
Ahhh.. I found out that I have to re-run `quasar dev` in order to make my own `env` variables work after installation. After re-running `quasar dev` everything works fine. Thanks!

**Comment by hawkeye64** [comment]
Perfect! Didn't even think of that, but yes, it's not dynamic with hmr. You **do** have to rebuild it.
